# This file is generated by BpyBuild.
# Do not modify this file directly, modify the PO files
# under MCprep_addon/MCprep_resources/Languages
MCPREP_TRANSLATIONS = {'ru_RU': {('*', '(UI already improved)'): '(UI уже улучшен)',
           ('*', 'Add effect'): 'Добавить эффект',
           ('*', 'Advanced'): 'Расширенные',
           ('*', 'Anonymous user tracking settings'): 'Настройки анонимного '
                                                      'отслеживания '
                                                      'пользователя',
           ('*', 'Change mob icon'): 'Изменить иконку моба',
           ('*', 'Click triangle to open'): 'Нажмите на треугольник, чтобы '
                                            'открыть',
           ('*', 'Combine Images'): 'Совместить Текстуры',
           ('*', 'Combine Materials'): 'Совместить Материалы',
           ('*', 'Cycles Optimizer'): 'Оптимизатор Cycles',
           ('*', 'Default Exporter:'): 'Экспортер по умолчанию:',
           ('*', 'Early access features and requests for feedback'): 'Функции '
                                                                     'раннего '
                                                                     'доступа '
                                                                     'и '
                                                                     'запросы '
                                                                     'на '
                                                                     'обратную '
                                                                     'связь',
           ('*', 'Effect folder'): 'Папка эффектов',
           ('*', 'Effects'): 'Эффекты',
           ('*', 'Effects folder'): 'Папка эффектов',
           ('*', 'Effects folder not found'): 'Файл эффектов не найден',
           ('*', 'Effects/collection folder not found'): 'Папка '
                                                         'эффектов/коллекции '
                                                         'не найдена',
           ('*', 'Effects/geonodes folder not found'): 'Папка эффектов/геонод '
                                                       'не найдена',
           ('*', 'Effects/particle folder not found'): 'Папка эффектов/частиц '
                                                       'не найдена',
           ('*', 'Enter object mode'): 'Войдите в объектный режим',
           ('*', 'Entity assets'): 'Ассеты энтити',
           ('*', 'Entity file'): 'Файл энтити',
           ('*', 'Entity file must be a .blend'): 'Файл энтити должен быть '
                                                  '.blend',
           ('*', 'Entity file not found'): 'Файл энтити не найден',
           ('*', 'For info on anonymous usage tracking:'): 'Для информации об '
                                                           'анонимном '
                                                           'отслеживании '
                                                           'использования:',
           ('*', 'Generate items from textures'): 'Сгенерировать предметы из '
                                                  'текстур',
           ('*', 'Generate models from .json files'): 'Сгенерировать модели из '
                                                      '.json файлов',
           ('*', 'Import Minecraft worlds'): 'Импорт Майнкрафт миров',
           ('*', 'Import pre-made blocks (e.g. lights)'): 'Импортировать '
                                                          'заранее созданные '
                                                          'блоки (например '
                                                          'свет)',
           ('*', 'Import pre-rigged entities'): 'Импортировать зариганных '
                                                'энтити',
           ('*', 'Import pre-rigged mobs & players'): 'Импортировать '
                                                      'заригганых мобов & '
                                                      'игроков',
           ('*', 'Improve UI'): 'Улучшить UI',
           ('*', 'Install file for mob spawning'): 'Установите файл для спавна '
                                                   'мобов',
           ('*', 'Install skin file for swapping'): 'Установить скин для смены',
           ('*', 'Install skins'): 'Установить скины',
           ('*', 'Install to folder'): 'Установить в папку',
           ('*', 'Learn MCprep + Blender, 1-minute tutorials'): 'Изучить '
                                                                'MCprep + '
                                                                'Blender, '
                                                                'одноминутные '
                                                                'туториалы',
           ('*', 'Load material'): 'Загрузить материал',
           ('*', 'Load mobs'): 'Загрузить мобов',
           ('*', 'Load spawners'): 'Загрузить спавнера',
           ('*', 'Load/generate effects'): 'Загрузить/сгенерировать эффекты',
           ('*', 'MCprep page for instructions and updates'): 'Страница MCprep '
                                                              'для инструкций '
                                                              'и обновлений',
           ('*', 'MCprep tools'): 'Инструменты MCprep',
           ('*', 'Mesh Swap'): 'Заменить Меш',
           ('*', 'MeshSwap file must be .blend'): 'Файл Meshswap должен быть '
                                                  '.blend',
           ('*', 'MeshSwap file must be a .blend'): 'Файл MeshSwap должен быть '
                                                    '.blend',
           ('*', 'MeshSwap file not found'): 'Файл MeshSwap не найден',
           ('*', 'Meshswap file'): 'Файл Meshswap',
           ('*', 'Meshswap file must be a .blend'): 'Файл MeshSwap должен быть '
                                                    '.blend',
           ('*', 'Meshswap file not found'): 'Meshswap файл не найден',
           ('*', 'Meshswap source:'): 'Источник Meshswap:',
           ('*', 'Meshwap assets'): 'Ассеты Meshswap',
           ('*', 'Mineways executable'): 'Mineways.exe',
           ('*', 'Mob (rig) spawning'): 'Спавн моба (рига)',
           ('*', 'Mob spawner folder'): 'Папка спавнера мобов',
           ('*', 'Mob spawning'): 'Спавн моба',
           ('*', 'No blocks loaded'): 'Блоки не загружены',
           ('*', 'No effects loaded'): 'Эффекты не загружены',
           ('*', 'No entities found!'): 'Энтити не найдены!',
           ('*', 'No entities loaded'): 'Энтити не загружены',
           ('*', 'No items found!'): 'Предметы не найдены!',
           ('*', 'No items loaded'): 'Предметы не загружены',
           ('*', 'No materials loaded'): 'Материалы не загружены',
           ('*', 'No meshswap blocks found!'): 'Не найдено ни одного блока '
                                               'meshswap!',
           ('*', 'No mobs in category,'): 'Мобов в категории нет,',
           ('*', 'No mobs loaded'): 'Мобы не загружены',
           ('*', 'No models found!'): 'Модели не найдены!',
           ('*', 'No models loaded'): 'Модели не загружены',
           ('*', 'No skins found'): 'Скины не найдены',
           ('*', 'No skins found/loaded'): 'Скины не найдены/загружены',
           ('*', 'No time controller,'): 'Нет контроллера времени,',
           ('*', 'OBJ incompatible with textureswap'): 'OBJ несовместим с '
                                                       'заменой текстур',
           ('*', 'OBJ world import'): 'Импорт OBJ мира',
           ('*', 'Open effects folder'): 'Открыть папку эффектов',
           ('*', 'Open mob folder'): 'Открыть папку мобов',
           ('*', 'Open rig folder'): 'Открыть папку ригов',
           ('*', 'Open skin folder'): 'Открыть папку скина',
           ('*', 'Open texture pack folder'): 'Открыть папку текстур пака',
           ('*', 'Open the Privacy Policy'): 'Открыть Политику '
                                             'Конфиденциальности',
           ('*', 'Opt OUT of anonymous usage tracking'): 'ОТКАЗАТЬСЯ от '
                                                         'анонимного '
                                                         'отслеживания '
                                                         'использования',
           ('*', 'Opt into anonymous usage tracking'): 'Принять анонимное '
                                                       'отслеживание '
                                                       'использования',
           ('*', 'Place block'): 'Разместить блок',
           ('*', 'Place item'): 'Поставить предмет',
           ('*', 'Prep Materials'): 'Подготовить материалы',
           ('*', 'Press to reload'): 'Нажмите, чтобы перезагрузить',
           ('*', 'Reload assets'): 'Перезагрузить ассеты',
           ('*', 'Reload mobs'): 'Перезагрузить мобов',
           ('*', 'Reload mobs below'): 'Перезагрузить мобов ниже',
           ('*', 'Reload skins'): 'Перезагрузить скины',
           ('*', 'Reload skins above'): 'Перезагрузить скины выше',
           ('*', 'Reset entity path'): 'Сбросить путь энтити',
           ('*', 'Reset meshswap path'): 'Сбросить путь meshswap',
           ('*', 'Resource pack'): 'Ресурс пак',
           ('*', 'Restart blender'): 'Перезапустите блендер',
           ('*', 'Rig Folder'): 'Папка ригов',
           ('*', 'Select exporter!'): 'Выберите экспортер!',
           ('*', 'Select skin'): 'Выбрать скин',
           ('*', 'Select/install mobs'): 'Выбрать/установить мобов',
           ('*', 'Skin Folder'): 'Папка Скина',
           ('*', 'Skin from file'): 'Скин из файла',
           ('*', 'Skin from username'): 'Скин по нику',
           ('*', 'Skin path'): 'Путь до скина',
           ('*', 'Skin swapping'): 'Смена скина',
           ('*', 'Spawn Entity'): 'Заспавнить Этити',
           ('*', 'Texture / Resource packs'): 'Текстура / Ресурс паки',
           ('*', 'Texture pack folder'): 'Папка текстур пака',
           ('*', 'Time of day'): 'Время дня',
           ('*', 'Tutorial Series'): 'Серия Гайдов',
           ('*', 'Unsure on how to use the addon? Check out these resources'): 'Не '
                                                                               'уверены '
                                                                               'как '
                                                                               'использовать '
                                                                               'аддон? '
                                                                               'Проверьте '
                                                                               'эти '
                                                                               'ресурсы',
           ('*', 'Using MCprep in experimental mode!'): 'Использование MCprep '
                                                        'в эксперементальном '
                                                        'режиме!',
           ('*', 'World Importing & Meshswapping'): 'Импортирование мира & '
                                                    'Meshswapping',
           ('*', 'World OBJ Exports Folder'): 'Папка экспорта obj миров',
           ('*', 'World Tools'): 'Инструменты мира',
           ('*', 'World exporter'): 'Экспортер мира',
           ('*', 'World settings and lighting'): 'Настройки и освещение мира',
           ('*', 'add dynamic MC world.'): 'добавьте динамический MC мир.',
           ('*', 'copy file to folder.'): 'скопируйте файл в папку',
           ('*', 'install a rig below or'): 'установите риг ниже или',
           ('*', 'jmc2obj executable'): 'jmc2obj.exe',
           ('*', 'jmc2obj/Mineways'): 'jmc2obj/Mineways',
           ('*', 'to complete update'): 'для завершения обновления',
           ('*', 'to use spawner'): 'чтобы использовать спавнер',
           ('*', 'will be made visible. Thank you for contributing.'): 'будут '
                                                                       'видимы. '
                                                                       'Спасибо '
                                                                       'за '
                                                                       'помощь.',
           ('*', '{h}:{m}, day {d}'): '{h}:{m}, день {d}'},
 'zh_CN': {('*', '(UI already improved)'): '（UI 已经改善)',
           ('*', 'Advanced'): '高级',
           ('*', 'Change mob icon'): '更改生物图标',
           ('*', 'Combine Images'): '合并图像',
           ('*', 'Combine Materials'): '合并材质',
           ('*', 'Cycles Optimizer'): 'Cycles 优化器',
           ('*', 'Enter object mode'): '进入对象模式',
           ('*', 'Import pre-rigged mobs & players'): '导入预设置的生物和玩家',
           ('*', 'Improve UI'): '改善 UI',
           ('*', 'Load material'): '加载材质',
           ('*', 'MCprep materials'): 'MCprep 材质',
           ('*', 'MCprep tools'): 'MCprep 工具',
           ('*', 'Mesh Swap'): '网格变形',
           ('*', 'MeshSwap file must be .blend'): '网格变形文件必须是.blend格式',
           ('*', 'MeshSwap file must be a .blend'): '网格变形文件必须是.blend格式',
           ('*', 'MeshSwap file not found'): '未找到网格变形文件',
           ('*', 'Meshswap file'): '网格变形文件',
           ('*', 'Meshswap file must be a .blend'): '网格变形文件必须是.blend格式',
           ('*', 'Meshswap file not found'): '未找到网格变形文件',
           ('*', 'Meshswap source:'): '网格变形源:',
           ('*', 'Mob spawner folder'): '生物生成器文件夹',
           ('*', 'No blocks loaded'): '未加载方块',
           ('*', 'No materials loaded'): '未加载材质',
           ('*', 'No mobs in category,'): '该类别中没有生物，',
           ('*', 'No mobs loaded'): '未加载生物',
           ('*', 'No skins found/loaded'): '未找到/加载皮肤',
           ('*', 'No time controller,'): '没有时间控制器，',
           ('*', 'OBJ incompatible with textureswap'): 'OBJ与纹理交换不兼容',
           ('*', 'OBJ world import'): '导入 OBJ 世界',
           ('*', 'Open mob folder'): '打开生物文件夹',
           ('*', 'Place block'): '放置方块2',
           ('*', 'Prep Materials'): '准备材质',
           ('*', 'Press to reload'): '"按下重新加载',
           ('*', 'Reload assets'): '重新加载资源',
           ('*', 'Reload mobs'): '重新加载生物',
           ('*', 'Reload mobs below'): '重新加载下方的生物',
           ('*', 'Reload skins'): '重新加载皮肤',
           ('*', 'Reload skins above'): '重新加载上方的皮肤',
           ('*', 'Reset meshswap path'): '重置网格变形路径',
           ('*', 'Resource pack'): '资源包',
           ('*', 'Select skin'): '选择皮肤',
           ('*', 'Skin Swapper'): '皮肤交换器',
           ('*', 'Skin from file'): '从文件导入皮肤',
           ('*', 'Skin from username'): '从用户名导入皮肤',
           ('*', 'Skin path'): '皮肤路径',
           ('*', 'Texture pack folder'): '材质包文件夹',
           ('*', 'Time of day'): '时间',
           ('*', 'World Imports'): '导入地图',
           ('*', 'World Tools'): '世界工具',
           ('*', 'World exporter'): '地图导出工具',
           ('*', 'World settings and lighting'): '世界设置和光照',
           ('*', 'add dynamic MC world.'): '请添加动态MC世界。',
           ('*', 'copy file to folder.'): '将文件复制到文件夹中。',
           ('*', 'install a rig below or'): '安装一个下方的预设或',
           ('*', 'to use spawner'): '以使用生成器'},
 'zh_HANS': {('*', '(UI already improved)'): '（UI 已经改善)',
             ('*', 'Advanced'): '高级',
             ('*', 'Change mob icon'): '更改生物图标',
             ('*', 'Combine Images'): '合并图像',
             ('*', 'Combine Materials'): '合并材质',
             ('*', 'Cycles Optimizer'): 'Cycles 优化器',
             ('*', 'Enter object mode'): '进入对象模式',
             ('*', 'Import pre-rigged mobs & players'): '导入预设置的生物和玩家',
             ('*', 'Improve UI'): '改善 UI',
             ('*', 'Load material'): '加载材质',
             ('*', 'MCprep materials'): 'MCprep 材质',
             ('*', 'MCprep tools'): 'MCprep 工具',
             ('*', 'Mesh Swap'): '网格变形',
             ('*', 'MeshSwap file must be .blend'): '网格变形文件必须是.blend格式',
             ('*', 'MeshSwap file must be a .blend'): '网格变形文件必须是.blend格式',
             ('*', 'MeshSwap file not found'): '未找到网格变形文件',
             ('*', 'Meshswap file'): '网格变形文件',
             ('*', 'Meshswap file must be a .blend'): '网格变形文件必须是.blend格式',
             ('*', 'Meshswap file not found'): '未找到网格变形文件',
             ('*', 'Meshswap source:'): '网格变形源:',
             ('*', 'Mob spawner folder'): '生物生成器文件夹',
             ('*', 'No blocks loaded'): '未加载方块',
             ('*', 'No materials loaded'): '未加载材质',
             ('*', 'No mobs in category,'): '该类别中没有生物，',
             ('*', 'No mobs loaded'): '未加载生物',
             ('*', 'No skins found/loaded'): '未找到/加载皮肤',
             ('*', 'No time controller,'): '没有时间控制器，',
             ('*', 'OBJ incompatible with textureswap'): 'OBJ与纹理交换不兼容',
             ('*', 'OBJ world import'): '导入 OBJ 世界',
             ('*', 'Open mob folder'): '打开生物文件夹',
             ('*', 'Place block'): '放置方块2',
             ('*', 'Prep Materials'): '准备材质',
             ('*', 'Press to reload'): '"按下重新加载',
             ('*', 'Reload assets'): '重新加载资源',
             ('*', 'Reload mobs'): '重新加载生物',
             ('*', 'Reload mobs below'): '重新加载下方的生物',
             ('*', 'Reload skins'): '重新加载皮肤',
             ('*', 'Reload skins above'): '重新加载上方的皮肤',
             ('*', 'Reset meshswap path'): '重置网格变形路径',
             ('*', 'Resource pack'): '资源包',
             ('*', 'Select skin'): '选择皮肤',
             ('*', 'Skin Swapper'): '皮肤交换器',
             ('*', 'Skin from file'): '从文件导入皮肤',
             ('*', 'Skin from username'): '从用户名导入皮肤',
             ('*', 'Skin path'): '皮肤路径',
             ('*', 'Texture pack folder'): '材质包文件夹',
             ('*', 'Time of day'): '时间',
             ('*', 'World Imports'): '导入地图',
             ('*', 'World Tools'): '世界工具',
             ('*', 'World exporter'): '地图导出工具',
             ('*', 'World settings and lighting'): '世界设置和光照',
             ('*', 'add dynamic MC world.'): '请添加动态MC世界。',
             ('*', 'copy file to folder.'): '将文件复制到文件夹中。',
             ('*', 'install a rig below or'): '安装一个下方的预设或',
             ('*', 'to use spawner'): '以使用生成器'}}
